apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: dns
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
  externalTrafficPolicy: Local