# ImagePolicy CRDs - Select latest image tag using timestamp numerical sorting
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-[a-f0-9]{7}-([0-9]{10})$'
    extract: '$1'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: backend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: backend
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-[a-f0-9]{7}-([0-9]{10})$'
    extract: '$1'
