---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vm-ssh-key
  namespace: website
spec:
  encryptedData:
    id_ed25519: AgB1HjW9aijVK9eUGKjJQ9/wxz/0r9BVTxFzvQSiJRtS91rKKz+vBHg7Vz08Q6Fz0tiqsKII+2b/soDIqE4WAh16GnOkgJWLGAwfaKQS8a6UDoLWgF/qD7ym7LwdcfPOH0MFFtWhRkUOCpo4zjIbexl54WShQZWiHPwTPoPqAMp8wGv9moXcXGLPAzZRwHO442iQNCxKDwe/Oe/Z/O9EujQSD2sbU9NJV3ppna4a6L/tsBxalG+lAS3mCeRj12A4FHO/kzjgItEgmJ2YTtrzgGsgrYF67ExVhGj2/kSGDwluZkv/BUj1OsMxAS67fjalfYKBKvFVwer6I5dnztkTr3jx663prgy8Su3GqOAGPDKAA2TY2KJFlyRLljUH26yMbRWzRAI4b71FpkACTwLC8Rvifaw6lg0+2Cx+/pfvmy/pbsIQkvxg4V0STm+z8NF+0PPdUR98DV3iZzOrU3tvYywAZ0oVnoM2CnLH4tddToa0kEjTAD8Dw6zKZfZxShF9a0fiCwbnaQj/jnKSsO710N7PbuyeFFhfZEV2daVRiSgzjvjX3mdvg7jYkEczEvWvRSG0BSyvPa8GwFpswIfHnx/yc34UJZ+H55vcAMfCDbsWrwe8jqF9AY0k/am5z8nZUzmfeLPyBMdxDgK2225rlOKrfFUw35I3iVJUwOE/3ANie3b5ev/xnEDH9eQ5H+NziVRIz9vri4h0kocBp2CKVUvNq5QgQG3dYjEer/R1qzHyfM3FJOc+xT7gd1xMiKyO3c3LStXSS+6zb6vD/8c4P6s7PW04qCx58ufzUhdm45ol4MDNyP2KpqFXWQkkWKOZBg2c60vox65bLH55mFSrr30jP1iofXlcwE66Y3ZbYiKN7k/CponixymUxCSk/KlNTtaS48LK6UAPQpjgyHExj8Jij+rcvn+/oYl3p/yb/YOfI9JagSEc0aYzoVN8hiGGNX7i/Stks6UpDbmD3UqNJW7vRo9zWQouTKsm8zQpclHz3S5Hv4LYKRGUNiKV2f2T7xlBTHROAH0okEGAr0Q6kqVLO+Z1A2MVJysDLF7ADwEPE/g2YBO0TMW7VCKEzcTabTR9TrJWx4xdoWFwbPFCTaHahyR7DMUP9HLypiDQiARr36qxl8eqvHH9Gnh88pJKILQIUFndQ4L1tNs0IkvlidWsGKc2q9/cSqdxxrsDaGrOqj3zEZa7IQn/UsIZ7pWOL2eSEqpFtYvX2gJsLOyLJOv7P6DpiXleMjFsYkU=
  template:
    metadata:
      creationTimestamp: null
      name: vm-ssh-key
      namespace: website
