-- User Roles Migration
-- Stores role assignments for Supabase Auth users
-- Created: 2026-01-29

-- user_roles table
-- Links auth.users to application roles
CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'customer')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, role)
);

-- Enable RLS
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- RLS Policies:
-- 1. Service role has full access (for admin operations)
CREATE POLICY "Service role has full access" ON public.user_roles
  FOR ALL USING (auth.jwt()->>'role' = 'service_role');

-- 2. Users can read their own roles (for client-side role checks)
CREATE POLICY "Users can read own roles" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);

-- Index for fast lookups by user_id
CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);

-- Comment for documentation
COMMENT ON TABLE public.user_roles IS 'Stores user role assignments for authorization. Roles are added to JWT via Auth Hook.';
